### ISSUE TITLE
rails throws vague error to the user when they attempt to autogen a call list if autogen is not checked

### ISSUE THREAD

**Issue by poblahblahblah** [darrendao/ringring#14] opened 2012-10-08 23:35 UTC
rails throws a vague error to the user when the user tries to run the oncall auto generation when they have checked the box to allow for auto generation.

an error page would be nice, although I imagine just hiding the auto generate stuff from the user if they have not set the list to be autogenerated would work as well.

**Comment by porcupie** [comment] 2012-12-20 00:37
I'm assuming Pat fixed this and Darren had merged the fix into master?  I could not reproduce the error ...

**Closed as completed by porcupie** 2012-12-20 00:37 UTC
